src/chapter6/beans/UserComment.java
package chapter6.beans;

import java.io.Serializable;
import java.util.Date;

public class UserComment implements Serializable {

    private int id;
    private String account;
    private String name;
    private int userId;
    private String text;
    private int messageId;
    private Date created_date;

    // getter/setterは省略されているので、自分で記述しましょう。

    public int getId() {
    	return id;
    }
    public void setId(int id) {
    	this.id = id;
    }

    public String getAccount() {
    	return account;
    }

    public void setAccount(String account) {
    	this.account = account;
    }

    public String getName() {
    	return name;
    }

    public void setName(String name) {
    	this.name = name;
    }

    public int getUserId() {
    	return userId;
    }

    public void setUserId(int userId) {
    	this.userId = userId;
    }

    public String getText() {
    	return text;
    }

    public void setText(String text) {
    	this.text = text;
    }

    public int getMessageId() {
    	return messageId;
    }

    public void setMessageId(int messageId) {
    	this.messageId = messageId;
    }

    public Date getCreatedDate() {
    	return created_date;
    }
    public void setCreatedDate(Date created_date) {
    	this.created_date = created_date;
    }

}

src/chapter6/controller/EditServlet.java
//つぶやきの編集のServlet
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.Message;
import chapter6.service.MessageService;

@WebServlet(urlPatterns = { "/edit" })
public class EditServlet extends HttpServlet {

	//編集したいつぶやきidを選択。doGetメソッド…値を取ってくるとき
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

    	//ﾊﾟﾗﾒｰﾀ(JSP)でﾘｸｴｽﾄされたﾒｯｾｰｼﾞIDを取得
    	String messageId = request.getParameter("messageId");

    	//DBの情報をmessageに代入
    	Message message = new MessageService().select(messageId);

    	HttpSession session = request.getSession();
    	List<String> errorMessages = new ArrayList<String>();

    	if(message == null) {
    		 errorMessages.add("不正なパラメータが入力されました");
    		 session.setAttribute("errorMessages", errorMessages);
    		 response.sendRedirect("./");
    		 return;
    	}

        //Editｻｰﾌﾞﾚｯﾄ処理後に表示するJSPに転送する
        request.setAttribute("message", message);
        request.getRequestDispatcher("edit.jsp").forward(request, response);
    }

    //doPostメソッド…DBに変更、修正、更新を加えるとき
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        //String型のerrorMessageというﾘｽﾄを生成。
        List<String> errorMessages = new ArrayList<String>();

        //入力されたつぶやきをﾊﾟﾗﾒｰﾀで受け取っている。
        String text = request.getParameter("text");

        //ﾊﾟﾗﾒｰﾀでﾘｸｴｽﾄされたﾒｯｾｰｼﾞIDを取得
        String messageId = request.getParameter("messageId");


        //ﾊﾞﾘﾃﾞｰｼｮﾝ。ｾｯｼｮﾝに値をｾｯﾄする。textとerrorMessagesが無効の場合
        if (!isValid(text, errorMessages)) {
        	Message message = new MessageService().select(messageId);

        	request.setAttribute("errorMessages", errorMessages);

            //sessionにtextという名前を付けたつぶやきを格納。ﾘｸｴｽﾄの範囲で値を保持。
        	request.setAttribute("message", message);
            request.getRequestDispatcher("edit.jsp").forward(request, response);

            return;
        }

        // messageにedit.jspで入力されたつぶやきを代入
        Message message = new Message();
        message.setText(text);
        message.setId(Integer.parseInt(messageId));

        //メッセージの更新
        new MessageService().update(message);

        //処理中のページから別のページ(ファイル)へ処理を移す
        response.sendRedirect("./");
    }

    //オブジェクトが閉じられておらず、有効であるかどうかを示します
    private boolean isValid(String text, List<String> errorMessages) {

    	//つぶやきの記入がなかったらｴﾗｰ表示
        if (StringUtils.isBlank(text)) {
            errorMessages.add("メッセージを入力してください");
        //
        } else if (140 < text.length()) {
            errorMessages.add("140文字以下で入力してください");
        }

        if (errorMessages.size() != 0) {
            return false;
        }
        return true;
    }
}

src/chapter6/controller/LoginServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import chapter6.beans.User;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        request.getRequestDispatcher("login.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        String accountOrEmail = request.getParameter("accountOrEmail");
        String password = request.getParameter("password");

        User user = new UserService().select(accountOrEmail, password);
        if (user == null) {
            List<String> errorMessages = new ArrayList<String>();
            errorMessages.add("ログインに失敗しました");
            request.setAttribute("errorMessages", errorMessages);
            request.getRequestDispatcher("login.jsp").forward(request, response);
            return;
        }

        HttpSession session = request.getSession();
        session.setAttribute("loginUser", user);
        response.sendRedirect("./");
    }
}

src/chapter6/controller/SettingServlet.java
package chapter6.controller;
//ユーザー情報変更画面(設定)のServlet

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.User;
import chapter6.exception.NoRowsUpdatedRuntimeException;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/setting" })
public class SettingServlet extends HttpServlet {

    private HttpServletRequest request;

	@Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

    	//セッションを取得。システムの一連の流れ。処理の中での値を取ってくる。
        HttpSession session = request.getSession();
        //セッションから値を取得。ﾛｸﾞｲﾝﾕｰｻﾞｰ＝自分
        User loginUser = (User) session.getAttribute("loginUser");

        //userに自分の値を代入
        User user = new UserService().select(loginUser.getId());

        request.setAttribute("user", user);
        request.getRequestDispatcher("setting.jsp").forward(request, response);
    }

	//エラーメッセージの表示
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        HttpSession session = request.getSession();
        List<String> errorMessages = new ArrayList<String>();

        User user = getUser(request);
        if (isValid(user, errorMessages)) {
            try {
                new UserService().update(user);
            } catch (NoRowsUpdatedRuntimeException e) {
                errorMessages.add("他の人によって更新されています。最新のデータを表示しました。データを確認してください。");
            }
        }

        if (errorMessages.size() != 0) {
            request.setAttribute("errorMessages", errorMessages);
            request.setAttribute("user", user);
            request.getRequestDispatcher("setting.jsp").forward(request, response);
            return;
        }

        session.setAttribute("loginUser", user);
        response.sendRedirect("./");
    }

    //userインスタンスを生成。値をセットしuserに返す。
    private User getUser(HttpServletRequest request) throws IOException, ServletException {

        User user = new User();
        user.setId(Integer.parseInt(request.getParameter("id")));
        user.setName(request.getParameter("name"));
        user.setAccount(request.getParameter("account"));
        user.setPassword(request.getParameter("password"));
        user.setEmail(request.getParameter("email"));
        user.setDescription(request.getParameter("description"));
        return user;
    }

    //SQLが閉じられておらず、有効であるかどうかを示す。
    private boolean isValid(User user, List<String> errorMessages) {

        String name = user.getName();
        String account = user.getAccount();
        String email = user.getEmail();
        int id = user.getId();

        //ﾕｰザｰ型の情報が返ってくる。//返ってきた値を代入
        User checkUser = new UserService().select(account);


        //isEmpty→空文字判定
        if (!StringUtils.isEmpty(name) && (20 < name.length())) {
            errorMessages.add("名前は20文字以下で入力してください");
        }
        if (StringUtils.isEmpty(account)) {
            errorMessages.add("アカウント名を入力してください");
        } else if (20 < account.length()) {
            errorMessages.add("アカウント名は20文字以下で入力してください");
        } else if ((checkUser != null) && checkUser.getId() != id) {
        	errorMessages.add("このアカウント名は既に使われています");
        }
        if (!StringUtils.isEmpty(email) && (50 < email.length())) {
            errorMessages.add("メールアドレスは50文字以下で入力してください");
        }
        if (errorMessages.size() != 0) {
            return false;
        }
        return true;
    }
}

src/chapter6/controller/SignUpServlet.java
package chapter6.controller;
//ユーザー登録画面のServlet

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.User;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/signup" })
public class SignUpServlet extends HttpServlet {

    @Override //getの場合signup.jspを表示
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

    	//処理の転送
        request.getRequestDispatcher("signup.jsp").forward(request, response);
    }

    @Override //Post場合、Serviceﾒｿｯﾄﾞを呼び出してDBへﾕｰｻﾞｰ登録する。
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

    	//ｴﾗｰﾒｯｾｰｼﾞﾘｽﾄを作成
        List<String> errorMessages = new ArrayList<String>();

        //
        User user = getUser(request);
        if (!isValid(user, errorMessages)) {
            request.setAttribute("errorMessages", errorMessages);

            //ユーザー登録が完了したら、TOPJSPを表示
            request.getRequestDispatcher("signup.jsp").forward(request, response);
            return;
        }

        new UserService().insert(user);
        //ﾘﾀﾞｲﾚｸﾄして画面表示。フォームデータの2重送信防止(PRGﾊﾟﾀｰﾝ)。
        response.sendRedirect("./");
    }

    private User getUser(HttpServletRequest request) throws IOException, ServletException {

        User user = new User();
        user.setName(request.getParameter("name"));
        user.setAccount(request.getParameter("account"));
        user.setPassword(request.getParameter("password"));
        user.setEmail(request.getParameter("email"));
        user.setDescription(request.getParameter("description"));
        return user;
    }

    private boolean isValid(User user, List<String> errorMessages) {

    String name = user.getName();
        String account = user.getAccount();
        String password = user.getPassword();
        String email = user.getEmail();


        //ﾕｰザｰ型の情報が返ってくる
        new UserService().select(account);
        //返ってきた値を代入
        User checkUser =  new UserService().select(account);

        if (!StringUtils.isEmpty(name) && (20 < name.length())) {
            errorMessages.add("名前は20文字以下で入力してください");
        }

        if (StringUtils.isEmpty(account)) {
            errorMessages.add("アカウント名を入力してください");
        } else if (20 < account.length()) {
            errorMessages.add("アカウント名は20文字以下で入力してください");
        } else if (checkUser != null) {
        	errorMessages.add("このアカウント名は既に使われています");

        }
        if (StringUtils.isEmpty(password)) {
            errorMessages.add("パスワードを入力してください");
        }

        if (!StringUtils.isEmpty(email) && (50 < email.length())) {
            errorMessages.add("メールアドレスは50文字以下で入力してください");
        }

        if (errorMessages.size() != 0) {
            return false;
        }
        return true;
    }
}

src/chapter6/controller/TopServlet.java
package chapter6.controller;
//TOP画面表示のサーブレット

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import chapter6.beans.User;
import chapter6.beans.UserComment;
import chapter6.beans.UserMessage;
import chapter6.service.CommentService;
import chapter6.service.MessageService;

//ｱﾉﾃｰｼｮﾝ /index.jspというURLと対応(ﾘｸｴｽﾄがあったら実行される)
@WebServlet(urlPatterns = { "/index.jsp" })

//HttpServletクラスを継承。ﾘｸｴｽﾄを受信し、ﾚｽﾎﾟﾝｽを返すための受け口。
public class TopServlet extends HttpServlet {

	//通常ｵｰﾊﾞｰﾗｲﾄﾞする
    @Override
    //ﾛｸﾞｲﾝのﾘｸｴｽﾄを受け取るメソッド。HttpServlet = ﾘｸｴｽﾄを受信し、ﾚｽﾎﾟﾝｽを返すための受け口
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

    	//isShowMessageFormにfalseを代入
        boolean isShowMessageForm = false;

        //TOPJSPから入力されたloginUserの値をuserに代入。
        User user = (User) request.getSession().getAttribute("loginUser");

        //ﾛｸﾞｲﾝﾕｰｻﾞｰがnullでなかったら
        if (user != null) {
            isShowMessageForm = true;
        }

        //String型のuser_idの値をrequest.getParameter("user_id")でJSPから受け取るように設定
        String userId = request.getParameter("user_id");
        String start = request.getParameter("start");
        String end = request.getParameter("end");


        //MessageServiceのgetMessageに引数としてString型のuser_idを追加
        List<UserMessage> messages = new MessageService().select(userId, start, end);

        boolean isShowCommentForm = false;
        if (user != null) {
        	isShowCommentForm = true;
        }
        List<UserComment> comments = new CommentService().select();

        System.out.println(comments.get(0).getText());


        //ﾘｸｴｽﾄにmessagesというｷｰで値をセット ServletとJSPから参照できる
        request.setAttribute("messages", messages);
        request.setAttribute("isShowMessageForm", isShowMessageForm);

        //ﾘｸｴｽﾄにｺﾒﾝﾄをｾｯﾄ jsp側に渡す
		request.setAttribute("comments", comments);
        request.setAttribute("isShowCommentForm", isShowCommentForm);
        request.setAttribute("startDate", start);
        request.setAttribute("endDate", end);
        request.getRequestDispatcher("/top.jsp").forward(request, response);

    }
}

WebContent/edit.jsp
<%-- つぶやきの編集画面のJSP --%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<%-- ﾛｸﾞｲﾝ時エラーが起きたときエラー表示 --%>
	<c:if test="${ not empty errorMessages }">
    	<div class="errorMessages">
       		<ul>
        		<%-- Servlet上で errorMessages というｷｰに--%>
        		<%-- 繰り返しでｴﾗｰﾒｯｾｰｼﾞを表示 --%>
            	<c:forEach items="${errorMessages}" var="errorMessage">
                	<li><c:out value="${errorMessage}" />
            	</c:forEach>
        	</ul>
    	</div>
	</c:if>

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>つぶやきの編集画面</title>
	</head>

	<body>
		<div class ="edit-area">
			<%-- editServletのpostメソッドへ送る --%>
			<form action="edit" method="post">
				編集内容<br />
				<%-- ${message.text}で編集前のつぶやきを表示 --%>
        		<textarea name="text" cols="100" rows="5" class="tweet-box">${message.text}</textarea>
        		<br />
        		<input name="messageId" value="${message.id}" id="id" type="hidden"/>
        		<input type="submit" value="更新">（140文字まで)
       			<br>
       			<%-- ./ = ﾃﾞﾌｫﾙﾄに設定(topjsp)に戻る --%>
        		<a href="./">戻る</a>
    		</form>
		</div>
	</body>
</html>

WebContent/login.jsp
<%-- ログイン画面のJSP --%>
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>ログイン</title>
        <link href="./css/style.css" rel="stylesheet" type="text/css">
    </head>

    <body>
        <div class="main-contents">
            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="errorMessage">
                            <li><c:out value="${errorMessage}" />
                        </c:forEach>
                    </ul>
                    <c:remove var="errorMessages" scope="session" />
                </div>
            </c:if>

            <form action="login" method="post"><br />
                <label for="accountOrEmail">アカウント名かメールアドレス</label>
                <input name="accountOrEmail" id="accountOrEmail"/> <br />

                <label for="password">パスワード</label>
                <input name="password" type="password" id="password"/> <br />

                <input type="submit" value="ログイン" /> <br />
                <a href="./">戻る</a>
            </form>

            <div class="copyright"> Copyright(c)AnzuOkuhara</div>
        </div>
    </body>
</html>

WebContent/top.jsp
<%-- TOP画面のJSP --%>
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
    	<%-- --%>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>簡易Twitter</title>
		<link href="./css/style.css" rel="stylesheet" type="text/css">
		<script src = "https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js" ></script>
		<script>
			$(function() {
				$('#delete').on('click',function() {
        		alert('本当に削除しますか');
        		});
			});
		</script>
	</head>

    <body>
    	<%-- main-contentsとheaderというdivのまとまり--%>
        <div class="main-contents">
        	<div class="header">

        		<%-- test属性(必須)にはEL式で判定条件を指定 empty=空文字判定(nullかどうか)--%>
    			<c:if test="${ empty loginUser }">

        			<%-- a href=ｱﾝｶｰﾀﾞｸﾞのｴｲﾁﾚﾌ … ﾘﾝｸ先を指定--%>
        			<a href="login">ログイン</a>
       				<a href="signup">登録する</a>
    			</c:if>

    			<%-- ﾛｸﾞｲﾝしている状態 --%>
   				<c:if test="${ not empty loginUser }">
       				<a href="./">ホーム</a>
       				<a href="setting">設定</a>
       				<a href="logout">ログアウト</a>
       			</c:if>
       		</div>

		<%-- 日付絞り込み入力欄 --%>
		<div class="date-form">
				<form action="./" method="get">
					<%-- type属性でtype=dateを指定し日付の入力欄を作成 --%>
					日付 <input type="date" name="start" value = "${startDate}" min = "2021-03-01">
					～<input type="date" name="end" value = "${endDate}">
					<input type="submit" value="絞込">
				</form>
		</div>

		<%-- loginUserが空でなかったら出力 --%>
		<c:if test="${ not empty loginUser }">
		<%-- 人間が分かりやすくするためにｸﾗｽでまとめている --%>
    		<div class="profile">
    			<%-- c:out=出力ﾀｸﾞ --%>
        		<div class="name"><h2><c:out value="${loginUser.name}" /></h2></div>
        		<div class="account">@<c:out value="${loginUser.account}" /></div>
        		<div class="description"><c:out value="${loginUser.description}" /></div>
			</div>
		</c:if>

		<%-- ﾛｸﾞｲﾝ時エラーが起きたときエラー表示 --%>
    	<div class="errorMessages">
    		<c:if test="${ not empty errorMessages }">

        		<ul><%-- ul = 箇条書きのリスト --%>

        			<%-- Servlet上で errorMessages というｷｰに--%>
        			<%-- 繰り返しでｴﾗｰﾒｯｾｰｼﾞを表示 --%>
            		<c:forEach items="${errorMessages}" var="errorMessages">
                		<li><c:out value="${errorMessages}" />
            		</c:forEach>
        		</ul>
        		<%-- ｴﾗｰﾒｯｾｰｼﾞの削除 --%>
    			<c:remove var="errorMessages" scope="session" />
    		</c:if>
    	</div>


		<div class="form-area">

			<%-- TopServretから 条件指定--%>
    		<c:if test="${ isShowMessageForm }">

    			<%-- ﾒｯｾｰｼﾞ画面に遷移 form action="message"=ﾒｯｾｰｼﾞ(messageServlet)というﾍﾟｰｼﾞに対してPOST--%>
        		<%-- formﾀｸﾞ=DBにﾃﾞｰﾀを送るとき使う。どこのﾍﾟｰｼﾞをどうする。  method=方法--%>
        		<form action="message" method="post">
            		いま、どうしてる？<br />
            		<%-- textareaﾀｸﾞ cols=横幅 rows=縦幅 class=名前--%>
            		<textarea name="text" cols="100" rows="5" class="tweet-box"></textarea>
            		<br />
            		<%-- inputﾀｸﾞ=formﾀｸﾞとｾｯﾄで使う。どうやって messageを通して処理 --%>
            		<%-- type=機能をつける submit=ﾒｯｾｰｼﾞを送る--%>
            		<input type="submit" value="つぶやく">（140文字まで）
        		</form>
    		</c:if>
		</div>

		<div class="messages">
			<%-- items=条件指定。ﾒｯｾｰｼﾞを引っ張て来ている--%>
    		<c:forEach items="${messages}" var="message">
        		<div class="message">
            		<div class="account-name">
                		<span class="account">

                			<%-- ｱｶｳﾝﾄ名を押してｱｶｳﾝﾄのつぶやき一覧表示。DBから。hlef=ﾘﾝｸ --%>
    						<a href="./?user_id=<c:out value="${message.userId}"/> ">
        						<c:out value="${message.account}" />
    						</a>
    					</span>
                		<span class="name"><c:out value="${message.name}" /></span>
            		</div>
            		<%-- ｱｶｳﾝﾄごとに表示 forEachで繰り返し --%>
            		<c:forEach var="messageNewLine" items="${fn:split(message.text, '
')}">
            			<div class="text"><c:out value = "${messageNewLine}" /></div>
            		</c:forEach>
 					<div class="date"><fmt:formatDate value="${message.createdDate}" pattern="yyyy/MM/dd HH:mm:ss" /></div>
					<%-- ボタンの横並び指示 --%>
					<div style="display:inline-flex">

						<%-- つぶやき編集ボタン --%>
						<c:if test = "${loginUser.id == message.userId}">
							<form action="edit" method="get">
								<%-- ${message.id}送っている --%>
            					<input name="messageId" value="${message.id}" id="id" type="hidden"/>
            	 				<input type="submit" value="編集" >
            				</form>
            				<pre>  </pre><%-- スペース --%>
        				</c:if>
        				<c:if test = "${loginUser.id == message.userId}">
							<%-- つぶやきの削除ボタン --%>
							<form action="deleteMessage" method="post">
								<%-- ${message.id}送っている  hidden=ﾌﾞﾗｳｻﾞ上で非表示にしたいときに使う--%>
            					<input name="messageId" value="${message.id}" id="id" type="hidden"/>
            					<input type="submit" value="削除" id = "delete" >
            				</form>
        				</c:if>
        			</div>

					<%-- コメントの返信を表示 --%>
					<div class="comments">

    					<c:forEach items="${comments}" var="comment">
        					<div class="comment">
            					<div class="account-name">
            						<c:if test = "${comment.messageId == message.id}">

                						<span class="account"><c:out value="${comment.account}" /></span>
                						<span class="name"><c:out value="${comment.name}" /></span>

											<%-- ﾃｷｽﾄの改行 --%>
                							<c:forEach var="commentNewLine" items="${fn:split(comment.text, '
')}">
 												<div class="text"><c:out value = "${commentNewLine}" /></div>
            								</c:forEach>
            							<div class="date"><fmt:formatDate value="${comment.createdDate}" pattern="yyyy/MM/dd HH:mm:ss" /></div>
        							</c:if>
        						</div>
        					</div>
   						</c:forEach>
					</div>

        			<div class="comment-area">
        				<c:if test="${ isShowCommentForm }">
							<%-- TopServretから 条件指定 ﾛｸﾞｲﾝしている状態なら見える--%>

    						<%-- ﾒｯｾｰｼﾞ画面に遷移 form action="comment"=ｺﾒﾝﾄ(commentServlet)というﾍﾟｰｼﾞに対してPOST--%>
        					<%-- formﾀｸﾞ=DBにﾃﾞｰﾀを送るとき使う。どこのﾍﾟｰｼﾞをどうする。  method=方法--%>
        					<form action="comment" method="post">
            					返信<br />

            					<%-- textareaﾀｸﾞ cols=横幅 rows=縦幅 class=名前--%>
            					<textarea name="reply" cols="100" rows="5" class="reply-box" ></textarea>


            					<br />
            					<%-- inputﾀｸﾞ=formﾀｸﾞとｾｯﾄで使う --%>
            					<input name="messageId" value="${message.id}" id="id" type="hidden"/>

            					<%-- type=機能をつける submit=ﾒｯｾｰｼﾞを送る--%>
            					<input type="submit" value="返信">
        					</form>
    					</c:if>
					</div>
    			</div>
    		</c:forEach>
		</div>
	</div>
    <div class="copyright"> Copyright(c)Anzu Okuhara</div>
    </body>
</html>